name: Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      PROJECT_NAME: Reload Feedback
      MODRINTH_ID: KmRgBUgi

    strategy:
      matrix:
        include:
          - SOURCE_FOLDER: src/1.13-1.21/${{ env.PROJECT_NAME }}
            GAME_VERSIONS: "[1.13,1.21)"
          - SOURCE_FOLDER: src/1.21+/${{ env.PROJECT_NAME }}
            GAME_VERSIONS: "[1.21,]"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Variables
        run: |
          set -euo pipefail

          VERSION=${GITHUB_REF_NAME#v}

          SOURCE_FOLDER="${{ matrix.SOURCE_FOLDER }}"

          OUTPUT_FILE_BASENAME="${PROJECT_NAME} v${VERSION}"
          OUTPUT_FILE_MODRINTH="${OUTPUT_FILE_BASENAME}.zip"
          OUTPUT_FILE_GITHUB="${OUTPUT_FILE_BASENAME// /-}.zip"

          echo "VERSION=${VERSION}" >> "$GITHUB_ENV"
          echo "SOURCE_FOLDER=${SOURCE_FOLDER}" >> "$GITHUB_ENV"
          echo "OUTPUT_FILE_MODRINTH=${OUTPUT_FILE_MODRINTH}" >> "$GITHUB_ENV"
          echo "OUTPUT_FILE_GITHUB=${OUTPUT_FILE_GITHUB}" >> "$GITHUB_ENV"

      - name: Extract Changelog
        id: changelog
        run: |
          set -euo pipefail

          changelog=$(awk "/^## \[v${VERSION//./\\.}\]/ {flag=1; next} /^## / {flag=0} flag" CHANGELOG.md)
          changelog="${changelog//'%'/'%25'}"

          if [ -z "$changelog" ]; then
            changelog="No changelog entry found for version ${VERSION}."
          fi

          echo "log<<EOF" >> "$GITHUB_OUTPUT"
          echo "${changelog}" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Zip Source Folder
        working-directory: ${{ env.SOURCE_FOLDER }}
        run: |
          set -euo pipefail

          zip -r "output" ./*
          cp "output" "$GITHUB_WORKSPACE/${{ env.OUTPUT_FILE_MODRINTH }}"
          cp "output" "$GITHUB_WORKSPACE/${{ env.OUTPUT_FILE_GITHUB }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ env.OUTPUT_FILE_GITHUB }}
          body: ${{ steps.changelog.outputs.log }}

      # - name: Publish Data Pack
      #   uses: Kir-Antipov/mc-publish@v3.3
      #   with:
      #     modrinth-id: ${{ env.MODRINTH_ID }}
      #     modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

      #     name: ${{ env.PROJECT_NAME }} v${{ env.VERSION }}
      #     version: ${{ env.VERSION }}
      #     changelog: ${{ steps.changelog.outputs.log }}
      #     files: ${{ env.OUTPUT_FILE_MODRINTH }}

      #     loaders: datapack
      #     version-type: release

      #     game-version-filter: releases
      #     game-versions: ${{ matrix.GAME_VERSIONS }}
